swagger: '2.0'
info:
  title: Integração Fluig para Criar Card no Trello
  description: Serviço para criar cards no Trello a partir de atividades no Fluig
  version: 1.0.0
paths:
  /createTrelloCard:
    post:
      summary: Cria um card no Trello
      description: Recebe dados do Fluig e cria um card no quadro Trello
      parameters:
        - name: title
          in: query
          description: O título do card
          required: true
          type: string
        - name: description
          in: query
          description: A descrição do card
          required: true
          type: string
      responses:
        200:
          description: Card criado com sucesso
        400:
          description: Erro ao criar o card
